version: "3.7"
services:
  #PHP Service
  frameapp:
    build:
      args:
        user: Azizul
        uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    image: frameapp
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - frameapp_network

  #MySQL Service
  frameapp_db:
    image: mysql:8.0
    container_name: frameapp_db
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - frameapp_mysql_data:/var/lib/mysql
    networks:
      - frameapp_network

  #Nginx Service
  frameapp_nginx:
    image: nginx:alpine
    container_name: frameapp_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_APP_PORT}:80"
      - "${DOCKER_APP_SSL_PORT}:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/certs:/etc/nginx/certs
    networks:
      - frameapp_network
  # phpmyadmin service
  frameapp_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: frameapp_phpmyadmin
    depends_on:
      - frameapp_db
    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: frameapp_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 300M
    networks:
      - frameapp_network

  frameapp_redis_cache:
    image: redis:alpine
    restart: always
    container_name: frameapp_redis_cache
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - frameapp_cache:/data
    networks:
      - frameapp_network

#Docker Networks
networks:
  frameapp_network:
    driver: bridge

#Volumes
volumes:
  frameapp_mysql_data:
  frameapp_cache:
